"""Shared constants for tests."""

# HTTP Status Codes
HTTP_OK = 200
HTTP_NOT_FOUND = 404
HTTP_UNPROCESSABLE_ENTITY = 422
HTTP_INTERNAL_SERVER_ERROR = 500

# Test Configuration
REQUEST_TIMEOUT = 30
DEBUG_TEXT_LENGTH = 100
DEFAULT_TEST_PORT = 8000
MAX_RETRIES = 30
