repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: .venv/bin/ruff format
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: .venv/bin/ruff check
        language: system
        types: [python]
        args: [--fix]